language: java
# try to fix the 'error' in request in Travis.
branches:
  except:
    - gh-pages

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2/repository

install: true

# don't do a two step like travis does: this is problematic due to Tycho refetching artifact.
script:
  - './mvnw install'

after_success:
  - cp -v site/index.md com.github.glhez.eclipse.releng.updatesite/target/repository

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: com.github.glhez.eclipse.releng.updatesite/target/repository
    github_token: $GITHUB_TOKEN
    on:
      branch: master
