language: java
jdk:
  - oraclejdk8
script: './mvnw clean install'
install: true
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: fr.glhez.eclipse.releng.updatesite/target/repository
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: site
    github_token: $GITHUB_TOKEN
    on:
      branch: master


