language: java
jdk:
  - oraclejdk8
script: 
  - './mvnw clean install'
  - cp -v site/index.md fr.glhez.eclipse.releng.updatesite/target/repository
install: true
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: fr.glhez.eclipse.releng.updatesite/target/repository
    github_token: $GITHUB_TOKEN
    on:
      branch: master
