language: java
jdk:
  - oraclejdk8
script: './mvnw clean install'
install: true
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: fr.glhez.eclipse.releng.updatesite/target/repository/  # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

