language: java
jdk:
  - oraclejdk8
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: fr.glhez.eclipse.releng.updatesite/target/repository/  # or remove this line to upload from root of repo
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

