name: Java CI and Publish with Maven
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
    - name: build
      run: |
        base64 --decode > "${KEYSTORE_PATH}" <<< "${{ secrets.KEYSTORE_DATA }}"
        ./mvnw -B verify -DperformRelease=true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_KEY }}
        KEYSTORE_PATH: ${{ github.workspace }}/code-signing.keystore"
    - name: Copy site index
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        cp -v site/index.md com.github.glhez.eclipse.releng.updatesite/target/repository
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
      with:
        branch: gh-pages
        folder: com.github.glhez.eclipse.releng.updatesite/target/repository

